export const ALL_BANKS = [
  { bank_name: "State Bank of India", short_name: "SBI" },
  { bank_name: "Bank of Baroda", short_name: "BOB" },
  { bank_name: "Punjab National Bank", short_name: "PNB" },
  { bank_name: "Canara Bank", short_name: "CANARA" },
  { bank_name: "Union Bank of India", short_name: "UBI" },
  { bank_name: "Bank of India", short_name: "BOI" },
  { bank_name: "Indian Bank", short_name: "IB" },
  { bank_name: "Central Bank of India", short_name: "CBI" },
  { bank_name: "Indian Overseas Bank", short_name: "IOB" },
  { bank_name: "UCO Bank", short_name: "UCO" },
  { bank_name: "Bank of Maharashtra", short_name: "BOM" },
  { bank_name: "Punjab & Sind Bank", short_name: "PSB" },
  { bank_name: "HDFC Bank", short_name: "HDFC" },
  { bank_name: "ICICI Bank", short_name: "ICICI" },
  { bank_name: "Axis Bank", short_name: "AXIS" },
  { bank_name: "Kotak Mahindra Bank", short_name: "KOTAK" },
  { bank_name: "Yes Bank", short_name: "YES" },
  { bank_name: "IndusInd Bank", short_name: "INDUSIND" },
  { bank_name: "IDFC FIRST Bank", short_name: "IDFC" },
  { bank_name: "Federal Bank", short_name: "FEDERAL" },
  { bank_name: "South Indian Bank", short_name: "SIB" },
  { bank_name: "RBL Bank", short_name: "RBL" },
  { bank_name: "Bandhan Bank", short_name: "BANDHAN" },
  { bank_name: "City Union Bank", short_name: "CUB" },
  { bank_name: "Karur Vysya Bank", short_name: "KVB" },
  { bank_name: "Karnataka Bank", short_name: "KB" },
  { bank_name: "DCB Bank", short_name: "DCB" },
  { bank_name: "Dhanlaxmi Bank", short_name: "DLB" },
  { bank_name: "Regional Rural Banks", short_name: "RRB" },
  { bank_name: "Small Finance Banks", short_name: "SFB" },
  { bank_name: "Payments Banks", short_name: "PB" },
  { bank_name: "Foreign Banks", short_name: "FOREIGN" }
];
